/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthorTag: typeof import('./../.vitepress/components/AuthorTag/index.vue')['default']
    GlassHome: typeof import('./../.vitepress/components/GlassHome/index.vue')['default']
  }
}
